# All available hooks: https://pre-commit.com/hooks.html
# R specific hooks: https://github.com/lorenzwalthert/precommit
default_stages: [pre-commit]
default_language_version:
  python: python3

repos:
  - repo: https://github.com/lorenzwalthert/precommit
    rev: v0.4.3.9009
    hooks:
      - id: style-files
        args:
          ['--ignore-start="^# styler: off$"', '--ignore-stop="^# styler: on$"']
      - id: lintr
        additional_dependencies:
          - r-lib/lintr
          - any::cyclocomp
      - id: roxygenize
        additional_dependencies:
          - dplyr
          - roxygen2
          - rlang
      - id: use-tidy-description
      - id: spell-check
      - id: readme-rmd-rendered
      - id: parsable-R
      - id: no-browser-statement
      - id: deps-in-desc
      - id: pkgdown
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ["--maxkb=20000"]
      - id: check-ast
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: check-executables-have-shebangs
      - id: detect-private-key
      - id: mixed-line-ending
      - id: file-contents-sorter
        files: "\\.Rbuildignore$"
      - id: end-of-file-fixer
      
ci:
  skip: [pkgdown]
  autoupdate_schedule: monthly
