library(datasets)
library(shiny)
library(plotly)
library(here)
library(bslib)
library(DT)
library(httr)
library(jsonlite)
library(tibble)
library(xml2)
library(tools)
library(dplyr)

httr::set_config(config(ssl_verifypeer = 0L))
