apiVersion: apps/v1
kind: Deployment
metadata:
  name: r-pipelines-models
  labels:
    app: r-pipelines
spec:
  replicas: 1
  selector:
    matchLabels:
      app: r-pipelines
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: r-pipelines
    spec:
      containers:
        - image: ghcr.io/plant-food-research-open/shiny-rpipelines:0.1.0
          resources:
            requests:
              memory: "2Gi"
              cpu: "300m"
          imagePullPolicy: Always
          name: shiny-random-forest
          ports:
            - containerPort: 3838
              protocol: TCP
          args:
            - R
            - -e
            - shiny::runApp('/app', launch.browser = FALSE, host = '0.0.0.0', port = 3838)
          env:
            - name: AWS_ACCESS_KEY_ID
              value: NZSA
            - name: AWS_SECRET_ACCESS_KEY
              value: NZSA
            - name: MODEL_CHOICES
              value: random_forest
            - name: MODEL_ENDPOINTS
              value: https://shiny.otago.ac.nz/NZSA-01-plumber
        - image: ghcr.io/plant-food-research-open/shiny-rpipelines:0.1.0
          resources:
            requests:
              memory: "1Gi"
              cpu: "300m"
          imagePullPolicy: Always
          name: random-forest
          ports:
            - containerPort: 8089
              protocol: TCP
          args:
            - Rscript
            - api/vetiver_deploy.R
          env:
            - name: S3_BUCKET
              value: data
            - name: AWS_ACCESS_KEY_ID
              value: NZSA
            - name: AWS_SECRET_ACCESS_KEY
              value: NZSA
            - name: S3_ENDPOINT_URL
              value: http://nzsa-s3:8080
            - name: MODEL_NAME
              value: random_forest
            - name: MODEL_PORT
              value: "8089"
            - name: MODEL_CARD_NAME
              value: random_forest_card
      restartPolicy: Always
