---
title: "Introduction"
authors: "James Bristow, Jingjing Zhang, Hana Liang, Lindy Guo, Tom Moore"
---

## Introduction

*Workshops on pipeline development and model deployment onto Kubernetes via Docker using R.*

## Tidymodels

### Introduction

This workshop provides an overview of pipeline development and model deployment using the tidymodels framework in R. We incorporate tidymodels-compatible packages such as *stacks*, *DALEX*, and *workflowsets*.

We include a light introduction to MLOps principles for model deployment using the *vetiver* and *plumber* R packages. We demonstrate containerisation of models using Docker for deployment onto Kubernetes.

### Helpful background knowledge

Some familiarity with R. Statistical/machine learning concepts such as cross-validation and hyper-parameter tuning.

### Coordinators

- Jingjing Zhang (Jingjing.Zhang@plantandfood.co.nz)
- Lindy Guo (Lindy.Guo@plantandfood.co.nz)
- Hana Liang (Yongqi.Liang@plantandfood.co.nz)
- James Bristow (James.Bristow@plantandfood.co.nz)

## Stan and Causal Inference

### Introduction

This workshop provides an overview of Bayesian modelling and causal inference using *brms* and *cmdstanr*. 

We include a light introduction to MLOps principles for model deployment using the *vetiver* and *plumber* R packages. We demonstrate containerisation of models using Docker for deployment onto Kubernetes.

### Helpful background knowledge

Some familiarity with R. Statistical concepts such as priors, posteriors, and Bayes' rule.

### Coordinators

- Tom Moore (Tom.Moore@plantandfood.co.nz)
- James Bristow (James.Bristow@plantandfood.co.nz)

