apiVersion: apps/v1
kind: Deployment
metadata:
  name: r-pipelines-models
  namespace: sandbox
  labels:
    app: r-pipelines
spec:
  replicas: 1
  selector:
    matchLabels:
      app: r-pipelines
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: r-pipelines
    spec:
      containers:
        - image: ghcr.io/plant-food-research-open/shiny-rpipelines:0.1.0
          imagePullPolicy: Always
          name: shiny
          ports:
            - containerPort: 3838
              protocol: TCP
          args:
            - R
            - -e
            - shiny::runApp('/app', launch.browser = FALSE, host = '0.0.0.0', port = 3838)
          env:
            - name: AWS_ACCESS_KEY_ID
              value: user
            - name: AWS_SECRET_ACCESS_KEY
              value: password
            - name: MODEL_CHOICES
              value: random_forest,gompertz
            - name: MODEL_ENDPOINTS
              value: https://random-forest.model.r-pipelines.k8s.dev.pfr.co.nz,https://gompertz.model.r-pipelines.k8s.dev.pfr.co.nz
        - image: ghcr.io/plant-food-research-open/shiny-rpipelines:0.1.0
          imagePullPolicy: Always
          name: random-forest
          ports:
            - containerPort: 8089
              protocol: TCP
          args:
            - Rscript
            - api/vetiver_deploy.R
          env:
            - name: S3_BUCKET
              value: data
            - name: AWS_ACCESS_KEY_ID
              value: user
            - name: AWS_SECRET_ACCESS_KEY
              value: password
            - name: S3_ENDPOINT_URL
              value: http://r-pipelines:9000
            - name: MODEL_NAME
              value: random_forest
            - name: MODEL_PORT
              value: "8089"
            - name: MODEL_CARD_NAME
              value: random_forest_card
        - image: ghcr.io/plant-food-research-open/shiny-rpipelines:0.1.0
          imagePullPolicy: Always
          name: gompertz
          ports:
            - containerPort: 8090
              protocol: TCP
          args:
            - Rscript
            - api/vetiver_deploy.R
          env:
            - name: S3_BUCKET
              value: data
            - name: AWS_ACCESS_KEY_ID
              value: user
            - name: AWS_SECRET_ACCESS_KEY
              value: password
            - name: S3_ENDPOINT_URL
              value: http://r-pipelines:9000
            - name: MODEL_NAME
              value: gompertz
            - name: MODEL_PORT
              value: "8090"
      restartPolicy: Always
