name: Build

on:
  release:
    types:
      - published
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  packages: write

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Package Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Docker push superset
        run: |
          docker compose build superset
          docker compose push superset
      - name: Docker push mlflow
        run: |
          docker compose build mlflow
          docker compose push mlflow
      - name: Docker push shiny
        run: |
          docker compose build shiny
          docker compose push shiny
