FROM rocker/binder:4.4.1 AS base

ARG BUILD_DATE

ARG APP_VERSION

ARG HOME=/home/rstudio

LABEL maintainer=james.bristow@plantandfood.co.nz

LABEL org.label-schema.build-date=$BUILD_DATE

LABEL version=$APP_VERSION

ENV HOME=$HOME

WORKDIR ${HOME}

USER root

COPY README.md README.md

ENV DEBIAN_FRONTEND=noninteractive \
    RENV_PATHS_ROOT=${HOME}/renv \
    RENV_PATHS_LIBRARY=${HOME}/renv/library \
    RENV_PATHS_CACHE=${HOME}/renv/.cache \
    RENV_CONFIG_REPOS_OVERRIDE=https://cloud.r-project.org \
    JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64/bin/java 

RUN apt-get update \
    && apt-get install -y --no-install-recommends openjdk-17-jdk pandoc libsodium-dev graphviz \
    libglpk-dev cmake libnng-dev libmbedtls-dev openssh-client liblzma-dev libpq-dev libcurl4-openssl-dev \
    libbz2-dev software-properties-common build-essential libmagic-dev libmagick++-dev curl g++ make \
    libharfbuzz-dev libfribidi-dev graphviz-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /tmp/downloaded_packages \
    && install2.r -e -n -1 --skipinstalled remotes \
    && R -e 'remotes::install_version("renv","1.0.7", repos = "https://cran.rstudio.com/")' \
    && R -e 'remotes::install_version("pak","0.7.2", repos = "https://cran.rstudio.com/")' \
    && R CMD javareconf -e 

FROM base AS r_builder

COPY renv.lock .renvignore .Rprofile ./

COPY renv ${HOME}/renv

RUN mkdir -p $RENV_PATHS_LIBRARY \
    && mkdir -p $RENV_PATHS_CACHE \
    &&  R -e \
    "options(renv.config.pak.enabled=TRUE, renv.consent=TRUE); renv::restore()" 

FROM base AS python_builder

ENV POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_IN_PROJECT=1 \
    POETRY_VIRTUALENVS_CREATE=1 \
    POETRY_CACHE_DIR=/tmp/poetry_cache \
    PATH="${HOME}/.local/bin:/root/.local/bin:$PATH"

COPY pyproject.toml poetry.lock ./

RUN curl -sSL https://install.python-poetry.org | python3 -\
    && poetry install --no-root --with dev \
    && rm -rf $POETRY_CACHE_DIR \
    && curl -sSL https://install.python-poetry.org | python3 - --uninstall

FROM base AS runtime

ENV R_LIBS=${HOME}/renv/library/R-4.4/x86_64-pc-linux-gnu \
    R_LIBS_SITE=${HOME}/renv/library/linux-ubuntu-jammy/R-4.4/x86_64-pc-linux-gnu \
    VIRTUAL_ENV=${HOME}/.venv \
    PATH="${HOME}/.venv/bin:$PATH"

COPY --chown=${NB_USER}:${NB_USER} ./app .

COPY --chown=${NB_USER}:${NB_USER} ./R ${HOME}/R

COPY --chown=${NB_USER}:${NB_USER} ./pages ${HOME}/pages

COPY --chown=${NB_USER}:${NB_USER} ./stan ${HOME}/stan

COPY --chown=rstudio:rstudio r-pipeline-development.Rproj .

COPY --from=r_builder --chown=${NB_USER}:${NB_USER} ${HOME} .

COPY --from=python_builder --chown=${NB_USER}:${NB_USER} /opt/venv ${VIRTUAL_ENV} 

RUN chown -R ${NB_USER}:${NB_USER} ${HOME} \
    && chmod -R 755 ${HOME} \
    && R -e "cmdstanr::install_cmdstan()" \
    && echo '.libPaths(c("/home/rstudio/renv/library/linux-ubuntu-jammy/R-4.4/x86_64-pc-linux-gnu", .libPaths()))' \
    >> /usr/local/lib/R/etc/Rprofile.site \
    && echo 'Sys.setenv(MAKEFLAGS = "-j1", CXXFLAGS = "-O1 -g0 -fno-inline -pipe")' \
    >> /usr/local/lib/R/etc/Rprofile.site \
    && echo 'CXXFLAGS=-O1 -g0 -fno-inline -pipe' >> /usr/local/lib/R/etc/Makeconf \
    && echo 'MAKEFLAGS=-j1' >> /usr/local/lib/R/etc/Makeconf

USER ${NB_USER}

EXPOSE 8787 8787
